### ISSUE TITLE
Inconsistent example of "acronyms should be treated as words".

### ISSUE THREAD

**Issue by laaph** [raywenderlich/c-sharp-style-guide#10]
There is a section that says "In code, acronyms should be treated as words", with an example of "Bad: XMLHTTPRequest, Good: XmlHttpRequest".  However, early in the document, there is an example of acronyms not being treated as words. "Namespaces are all PascalCase, multiple words concatenated together, without hypens ( - ) or underscores ( _ ):" and "Good: RayWenderlich.FPSGame.HUD.Healthbar".  

I would either like to see it explicit that namespaces (and other things? if so what other things) don't count as code, or it should be consistent as "RayWenderlich.FpsGame.Hud.Healthbar" (this doesn't seem right to me, most everyone uses upper case letters for their acronyms in namespaces, including Unity).

Thank you!

**Comment by BlackDragonBE** [comment]
I agree that uppercase acronyms should be permitted in namespaces. I'll discuss this with the rest of the team.

Thanks!

**Comment by BlackDragonBE** [comment]
I've changed the wording and the example of the Namespaces section. Thanks for the suggestion!
