### ISSUE TITLE
Property naming convention

### ISSUE THREAD

**Issue by sergebat** [raywenderlich/c-sharp-style-guide#12]
There seems to be no explicit guidelines for properties. `PascalCase`, same as methods?

**Comment by Dover8** [comment]
> There seems to be no explicit guidelines for properties. `PascalCase`, same as methods?

https://github.com/raywenderlich/c-sharp-style-guide#fields

**Comment by sergebat** [comment]
> https://github.com/raywenderlich/c-sharp-style-guide#fields

These are fields, right?

What about C# properties? It is quite common to use PascalCase for properties and camelCase for fields, but I don't see it explicitly covered, unless I miss something right in front of my eyes! :) 

```
    public string Name
    {
        get { return name; }
        set { name = value; }
    }
```

**Comment by BlackDragonBE** [comment]
> > https://github.com/raywenderlich/c-sharp-style-guide#fields
> 
> These are fields, right?
> 
> What about C# properties? It is quite common to use PascalCase for properties and camelCase for fields, but I don't see it explicitly covered, unless I miss something right in front of my eyes! :)
> 
> ```
>     public string Name
>     {
>         get { return name; }
>         set { name = value; }
>     }
> ```

Hi Sergei,

You're correct, properties use the same style as methods, PascalCase.
I'll add some clarification to the guide for this soon. Thanks for letting us know!

Cheers,
Eric

**Comment by Dover8** [comment]
> What about C# properties? It is quite common to use PascalCase for properties and camelCase for fields, but I don't see it explicitly covered, unless I miss something right in front of my eyes! :)

Ah yes. I would agree with in that context.

**Comment by BlackDragonBE** [comment]
I've added a Properties section.
