### ISSUE TITLE
Events: "methods" confusing; "On" breaks convention

### ISSUE THREAD

**Issue by JessyCatterwaul** [raywenderlich/c-sharp-style-guide#3]
The guide currently includes:
> Prefix event methods with the prefix On.

***event methods*** is not a standard term in C#, and so I was confused by what it was referring to.

I believe the examples suggest that the word _method_ should be left off of that sentence.

However, this suggestion breaks convention:
```c#
BAD: public static event CloseCallback Close;
GOOD: public static event CloseCallback OnClose;
```
 It even goes against the specific [MSDN example "use Close instead of OnClose"](https://msdn.microsoft.com/en-us/library/h0eyck3s(v=vs.71).aspx).

There is a convention for when to use the `On` prefix. [It is not for an event itself](http://stackoverflow.com/questions/18703490/does-the-prefix-on-in-the-name-of-the-c-sharp-methods-imply-anything), but for a protected (or occasionally private) method that calls the actual event, which has the same name, aside from the `On` prefix.

Should an example be made to show when to use `On`, or is that too heavy for this guide? I didn't yet find an example of Microsoft officially going into  when to use `On`, so it might be able to be left off for now. However, I think a link to that SO post, or one of the several similar ones, would be educational.

**Comment by BlackDragonBE** [comment]
I've switched the examples around and changed the wording so it now follows convention. I've decided to leave the intricacies of using the "On" prefix out of this guide.
