### ISSUE TITLE
Switch Statements default: always throw exception

### ISSUE THREAD

**Issue by ghost** [raywenderlich/c-sharp-style-guide#6]
Instead of never using default cases I would recommend to always throw an exception in the default case.
For example it's very easy to miss a new enum entry when it's used in multiple places.

**Comment by BlackDragonBE** [comment]
Hey Rickmey,

That's a great suggestion, I'll discuss this with the others.

Thanks!

**Comment by BlackDragonBE** [comment]
Changed the wording and added the default case. Thanks!
