### ISSUE TITLE
Translate for pt-br

### ISSUE THREAD

**Issue by anony000** [raywenderlich/c-sharp-style-guide#8]
I will translate this for the Portuguese language, have any problem?

**Comment by BlackDragonBE** [comment]
Hi there! Do you mean to copy the guide and host it on your own or add the translation to our repo?

Cheers

**Comment by anony000** [comment]
Add the translation to your repo. :)

**Comment by BlackDragonBE** [comment]
I've discussed this with Ray and we decided not to allow any translations at this time as we can't maintain them when we update the guide.
I suggest to open your own repo and add a translation with a link to the original in the meantime.
